export const order = [
  'hook',
  'title',
  'intro',
  // 'nurseroster',
  // 'wrong1',
  // 'wrong2',
  // 'wrong3',
  // 'wrong4',
  'certintro',
  // 'prooflogging',
  'proofchecker',
  'contribution',
  'plan',
  // 'pipeline',
  'gridsat',
  // 'gridsatsol',
  'grid',
  'gridmodel',
  'proofexpre',
  // 'grid1',
  // 'grid2',
  // 'grid3',
  // 'grid4',
  // 'grid5',
  // 'grid6',
  'grid7',
  'grid8',
  'grid9',
  'grid10',
  'grid11',
  'grid12',
  'grid13',
  // 'grid14',
  'proofcheckerdiagram',
  
  
  // 'afterproof',
  // 'midsummary',
  // 'notdone',
  // 'alldiff',
  // 'proofex',
  'grid15',
  'proofhow',
  // 'formalverif',
  // 'proof',
  // 'alldiffdef',
  // 'proofhow',
  // 'formalverifexample',
  // 'formalverifexpl',
  // 'formallimits',
  'contributionfocus1',
  // 'goals',
  'summary'
]

export const lastSlide = Math.max(0, order.length - 1)